### PR TITLE
fix 1D convolution and pooling

### PR DESCRIPTION
**Pull request by SnowWalkerJ**
I'm not sure. But it seems to work.
Fixed some shape issues of 1D convolution and pooling operations.

### CODE REVIEW

**Comment by aymericdamien** [comment]
Great, thanks! It looks like it is working too for me, I will try on some examples later to see if it has no issue.

**Comment by offbit** [comment]
With this addition it seems like every time stride is overwritten to stride=1. That doesn't seem like a correct behaviour. 
Does stride=2 works for you ?

**Comment by aymericdamien** [comment]
Ops, we may have skip a bug. Could you revert these changes about filter_size and strides and see if it fix your issue? https://github.com/tflearn/tflearn/pull/65/files#diff-ea93a7e2dbe37f5d963fc36e3135d39eL315

**Comment by offbit** [comment]
i've tried this change strides = [1, strides, 1, 1] and works fine.

**Pull request merged**
