### PR TITLE
add lstm generator that takes a text file as arg

### PR DESCRIPTION
**Pull request by JohnAllen**

### CODE REVIEW

**Comment by aymericdamien** [comment]
I am thinking, maybe we can also add temperature and the generated sequence length as extra parameter (if provided, otherwise let default values).
So user can execute:
```
# with default values
python lstm_generator_text_file.py
# with specific temperature and sequence length
python lstm_generator_text_file.py PATH -t 1.0 -l 200
```

**Comment by JohnAllen** [comment]
Sure good idea. Will add that shortly.

**Comment by JohnAllen** [comment]
I'm thinking of enforcing some temperature range so people don't run this for hours or days and then error out once it goes to print.  Any thoughts on what that range should be?

**Comment by aymericdamien** [comment]
Maybe just raise a Warning if out of range, I think people should be able to experiment with any value. A range between 0. and 2. should be fine.

**Comment by JohnAllen** [comment]
Hmm, wasn't sure how to modify this PR so submitting a fresh one.

**Pull request closed without merging**
